# Generated by Django 5.1.4 on 2025-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendancestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='venue',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
