# Generated by Django 5.1.4 on 2025-01-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attendance_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
