# Generated by Django 5.1.4 on 2025-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
