# Generated by Django 5.1.4 on 2025-02-27 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lecturer_email_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_unit', to='main.student')),
                ('units', models.ManyToManyField(related_name='students_units', to='main.unit')),
            ],
        ),
    ]
