# Generated by Django 5.1.4 on 2025-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_unit',
            name='unit',
        ),
        migrations.AlterField(
            model_name='studentunit',
            name='units',
            field=models.ManyToManyField(related_name='student_units', to='main.unit'),
        ),
        migrations.AddField(
            model_name='course_unit',
            name='unit',
            field=models.ManyToManyField(related_name='course_units', to='main.unit'),
        ),
    ]
