# Generated by Django 5.1.4 on 2025-03-03 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_course_unit_unit_alter_studentunit_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late')], default='on_time', max_length=20)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='main.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='main.student')),
            ],
            options={
                'unique_together': {('attendance', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceStudent',
        ),
    ]
