# Generated by Django 5.1.4 on 2026-04-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentattendancerecord_delete_attendancestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='main.school'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
