# Generated by Django 5.1.4 on 2024-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
